[package]
name = "todoctl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.22", features = ["cargo"] }
surrealdb = "1.0.0-beta.7"
tokio = "1.21.1"
